// AUTH
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// USER
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';

// PANTRY MANAGEMENT
export const SET_ACTIVE_PANTRY = 'SET_ACTIVE_PANTRY';
export const FETCH_PANTRIES = 'FETCH_PANTRIES';
export const CREATE_PANTRY = 'CREATE_PANTRY';
export const JOIN_PANTRY = 'JOIN_PANTRY';
export const DELETE_PANTRY = 'DELETE_PANTRY';

// ITEMS
export const FETCH_PANTRY_ITEMS = 'FETCH_PANTRY_ITEMS';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

